server:
  port: 8888
  tomcat:
    connection-timeout: 2s
    keep-alive-timeout: 15s
    threads:
      max: 50
      min-spare: 5

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/AhmerAtiq/catalog-service
          default-label: main
          searchPaths: config-repo
          timeout: 5
          clone-on-start: true 
          force-pull: true
          username: AhmerAtiq
          password: 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
